name: Deploy to VPS

on:
  push:
    branches: ["production"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Build Binary
        run: go build -ldflags '-s -w' -o main ./cmd/server/main.go

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          source: "main"
          target: "/home/fadhilkholaf/var/www/the-api/"
